twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_horizontal_layout.html.twig']

    paths:
        '%kernel.project_dir%/public/second_ver_assets/assets/img/': images

when@test:
    twig:
        strict_variables: true

