vich_uploader:
    db_driver: orm

    mappings:
        projects:
            uri_prefix: /second_ver_assets/assets/img
            upload_destination: '%kernel.project_dir%/public/second_ver_assets/assets/img'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
